Change the unavailable mercury repository for the github code base
CVC4/CVC4 pull request #4989
Opened 2020-09-01 16:07 UTC by mmuesly

The get-abc script failed as the `https://bitbucket.org/alanmi/abc` repository is no longer available.

It seems like the code moved to GitHub: https://github.com/berkeley-abc/abc

After a quick search in the git history, it seems like the commit https://github.com/berkeley-abc/abc/commit/3d7034bf619aada30b0ba1e8afcb151d304ab556 is the counterpart to the previously used changeset `53f39c11b58d`.  I adapt the install script to retrieve the code from GitHub instead of bitbucket.

In addition, the `cp --parents` command is not available on OSX by default. Therefore, I recommend to replace this with a `rsync`command on OSX.

2020-09-01 16:31 UTC, nafur requested changes
Thanks for the input!
I think we prefer not using git but download tarballs.

2020-09-01 16:31 UTC, nafur commented on contrib/get-abc
>  commit=53f39c11b58d
```suggestion
commit=3d7034bf619aada30b0ba1e8afcb151d304ab556
```

2020-09-01 16:31 UTC, nafur commented on contrib/get-abc
> +git checkout 3d7034bf
```suggestion
setup_dep "https://github.com/berkeley-abc/abc/archive/$commit.tar.gz" "$ABC_DIR"
cd "$ABC_DIR"
```

2020-09-01 19:28 UTC, mmuesly commented
@nafur thank you for reviewing my changes. I adopted it according to your suggestion.

2020-09-03 20:23 UTC, nafur approved these changes
This should be good. Could you please sign off your commit? (see https://github.com/CVC4/CVC4/wiki/Developer-Guide#pull-requests, in particular the "External contributor" part...)
Thanks!

2020-09-04 09:29 UTC, mmuesly commented
I added the signed-off line to the commit message.

2020-09-04 10:35 UTC, merged