Clean up nonlinear extension
CVC4/CVC4 pull request #5149
Opened 2020-09-28 11:50 UTC by nafur

This PR performs some cleanups in the nonlinear extension, in particular it removes the old lemma collection scheme. It is no longer needed, as all subsolvers use the inference manager.

2020-09-28 19:57 UTC, nafur commented
Benchmark results:
This PR has no effect with `--no-nl-ext`, but improves performance across the board with `--nl-ext`.

2020-09-28 21:21 UTC, ajreynol requested changes
This looks good, just a few minor requests.

2020-09-28 21:21 UTC, ajreynol commented on src/theory/arith/nl/nonlinear_extension.cpp
> +    unsigned count = d_im.numPendingLemmas() + d_im.numSentLemmas();
```suggestion
    size_t count = d_im.numPendingLemmas() + d_im.numSentLemmas();
```

2020-09-28 21:21 UTC, ajreynol commented on src/theory/arith/nl/nonlinear_extension.cpp
> +      unsigned count = d_im.numPendingLemmas() + d_im.numSentLemmas();
```suggestion
      size_t count = d_im.numPendingLemmas() + d_im.numSentLemmas();
```

2020-09-28 21:21 UTC, ajreynol commented on src/theory/arith/nl/nonlinear_extension.cpp
> +      unsigned count = d_im.numPendingLemmas() + d_im.numSentLemmas();
```suggestion
      size_t count = d_im.numPendingLemmas() + d_im.numSentLemmas();
```

2020-09-28 21:21 UTC, ajreynol commented on src/theory/arith/nl/nonlinear_extension.h
> +  bool modelBasedRefinement();
Can you update the documentation for this method (it doesnt add lemmas to lems)?

2020-09-29 12:05 UTC, ajreynol approved these changes

2020-09-29 12:05 UTC, merged