New proofs in arith::Constraint::externalExplain
CVC4/CVC4 pull request #5176
Opened 2020-10-01 05:53 UTC by alex-ozdemir

This commit threads proofs through the core of arith:
Constraint::externalExplain, which recursively explain arith literals.
One of the base cases here is asking the EE for an explanation, through
the congruence manager. To delay implementing proofs in
ArithCongruenceManager to a separate commit, we stub out proof
production in ArithCongruenceManager::explain for now.

2020-10-01 14:45 UTC, ajreynol requested changes
A few minor style-related requests.

2020-10-01 14:45 UTC, ajreynol commented on src/theory/arith/congruence_manager.cpp
> +  else
Remove redundant "else" after returns.

2020-10-01 14:45 UTC, ajreynol commented on src/theory/arith/constraint.cpp
> +    if (options::proofNew())
It's preferred not to check options during solving, can you update this based on checking e.g. if d_database has proofs enabled (which is the case if its proof node manager is non-null)?

2020-10-01 14:45 UTC, ajreynol commented on src/theory/arith/constraint.cpp
> +    if (options::proofNew())
Ditto.

2020-10-01 14:45 UTC, ajreynol commented on src/theory/arith/constraint.cpp
> +      if (options::proofNew())
Ditto.

2020-10-01 14:45 UTC, ajreynol commented on src/theory/arith/constraint.cpp
> +    if (options::proofNew())
Ditto.

2020-10-01 14:45 UTC, ajreynol commented on src/theory/arith/constraint.cpp
> +              d_database->d_pnm->mkNode(PfRule::ARITH_SCALE_SUM_UPPER_BOUNDS,
Nit: the code throughout would be a bit cleaner if you cached `ProofNodeManager * pnm = d_database->d_pnm`.

2020-10-01 14:45 UTC, ajreynol commented on src/theory/arith/congruence_manager.cpp
> +  else
Redundant else.

2020-10-01 15:48 UTC, alex-ozdemir commented
Thanks for the review, Andy. I think I've addressed most of your comments. Let me know if you see further possible improvements!

2020-10-01 17:53 UTC, ajreynol approved these changes
LGTM, remember to format.

2020-10-01 17:53 UTC, ajreynol commented on src/theory/arith/constraint.cpp
> +TrustNode ConstraintDatabase::eeExplain(const Constraint* const c) const{
Remember to format.

2020-10-02 01:07 UTC, alex-ozdemir commented on src/theory/arith/constraint.cpp
> +TrustNode ConstraintDatabase::eeExplain(const Constraint* const c) const{
Whoops. Thanks!

2020-10-02 13:03 UTC, merged