fix unit failures on debug without symfpu
CVC4/CVC4 pull request #5212
Opened 2020-10-06 17:26 UTC by yoni206

The following tests fail (locally) when compiling with debug and without symfpu:
```
unit/api/sort_black (Failed)
unit/theory/logic_info_white (Failed)
unit/util/floatingpoint_black (Child aborted)
```

This PR conditions the relevant parts of these tests to the availability of symfpu.

2020-10-06 23:28 UTC, aniemetz requested changes
For ` test/unit/util/floatingpoint_black.h `, use the guard (to disable everything if undefined)
```
#ifdef CVC4_USE_SYMFPU
....
#endif
```
Then it's not necessary to guard every single function.

2020-10-06 23:41 UTC, aniemetz requested changes

2020-10-06 23:41 UTC, aniemetz commented on test/unit/theory/logic_info_white.h
> +    {
```suggestion
```

2020-10-06 23:41 UTC, aniemetz commented on test/unit/theory/logic_info_white.h
> +      TS_ASSERT_EQUALS(info.getLogicString(), "SEP_AUFBVFPDTLRA");
```suggestion
     if (CVC4::Configuration::isBuiltWithSymFPU())
     {
       TS_ASSERT_EQUALS(info.getLogicString(), "SEP_AUFBVFPDTLRA");
     }
     else
     {
       TS_ASSERT_EQUALS(info.getLogicString(), "SEP_AUFBVDTLRA");
     }

2020-10-06 23:41 UTC, aniemetz commented on test/unit/theory/logic_info_white.h
> +    }
```suggestion
```

2020-10-06 23:41 UTC, aniemetz commented on test/unit/theory/logic_info_white.h
> +      TS_ASSERT_EQUALS(info.getLogicString(), "QF_SEP_AUFBVFPDTLRA");
```suggestion
     if (CVC4::Configuration::isBuiltWithSymFPU())
     {
       TS_ASSERT_EQUALS(info.getLogicString(), "QF_SEP_AUFBVFPDTLRA");
     }
     else
     {
       TS_ASSERT_EQUALS(info.getLogicString(), "QF_SEP_AUFBVDTLRA");
     }
```

2020-10-06 23:41 UTC, aniemetz commented on test/unit/theory/logic_info_white.h
> +      TS_ASSERT_EQUALS(info.getLogicString(), "QF_SEP_AUFFPLIA");
```suggestion
     if (CVC4::Configuration::isBuiltWithSymFPU())
     {
       TS_ASSERT_EQUALS(info.getLogicString(), "QF_SEP_AUFFPLIA");
     }
     else
     {
       TS_ASSERT_EQUALS(info.getLogicString(), "QF_SEP_AUFLIA");
     }
```

2020-10-07 15:32 UTC, martin-cs approved these changes

2020-10-07 23:38 UTC, yoni206 commented
OK I think I included your suggestions and addressed other comments (thanks also for the offline help). Please let me know if anything else is needed.

2020-10-07 23:54 UTC, aniemetz approved these changes

2020-10-08 00:20 UTC, merged