Add conversion of poly polynomial to cvc node.
CVC4/CVC4 pull request #5218
Opened 2020-10-07 07:37 UTC by nafur

This PR adds a new utility function to convert a `poly::Polynomial` back to a cvc4 Node.

2020-10-07 11:50 UTC, ajreynol requested changes
A few style issues.

2020-10-07 11:50 UTC, ajreynol commented on src/theory/arith/nl/poly_conversion.cpp
> +  VariableMapper& vm;
Remember to use `d_` for member data.

2020-10-07 11:50 UTC, ajreynol commented on src/theory/arith/nl/poly_conversion.cpp
> +  CollectMonomialData(VariableMapper& v) : vm(v) {}
This should be at the top of the struct.

2020-10-09 13:33 UTC, ajreynol commented on src/theory/arith/nl/poly_conversion.cpp
> +  VariableMapper& d_vm;
Can you give one line doc for these?

2020-10-09 15:35 UTC, nafur commented on src/theory/arith/nl/poly_conversion.cpp
> +  VariableMapper& d_vm;
Done.

2020-10-11 13:32 UTC, ajreynol approved these changes
LGTM

2020-10-11 16:22 UTC, merged