Implement bags evaluator
CVC4/CVC4 pull request #5294
Opened 2020-10-19 03:22 UTC by mudathirmahgoub

This PR implements `NormalForm::evaluate` for bags. 
This PR depends on PRs https://github.com/CVC4/CVC4/pull/5274 and  https://github.com/CVC4/CVC4/pull/5209

2020-10-19 03:24 UTC, mudathirmahgoub commented
The main changes are in files `normal_form.h`, `normal_form.cpp` and `theory_bags_normal_form_white`. The other changes are from PRs https://github.com/CVC4/CVC4/pull/5274 and https://github.com/CVC4/CVC4/pull/5209

2020-10-21 13:25 UTC, ajreynol requested changes
Mostly looks good, can you rebase this to master now?
A few minor requests.

2020-10-21 13:25 UTC, ajreynol commented on src/theory/bags/normal_form.cpp
> +    Assert(n[0].getKind() == kind::MK_BAG);
Maybe also assert in this loop that element is not already in elements.

2020-10-21 13:25 UTC, ajreynol commented on src/theory/bags/normal_form.cpp
> +  Assert(n.getKind() == MK_BAG && !n.isConst()
Can you give a comment here why this is the case?  I assume it is because you only call this on non-constants.

2020-10-21 13:25 UTC, ajreynol commented on src/theory/bags/normal_form.cpp
> +  if (n[0].getKind() == EMPTYBAG)
Can remove these 4 lines.

2020-10-21 17:52 UTC, closed without merging