(proof-new) Proofs for non-clausal simplification
CVC4/CVC4 pull request #5409
Opened 2020-11-10 13:45 UTC by ajreynol

Adds proof support in non-clausal simplification, connecting the proofs from circuit propagator.

2020-11-12 10:14 UTC, nafur requested changes
I know this stuff was not introduced with this PR, but I find it bad enough to change it right here and now :-)

2020-11-12 10:14 UTC, nafur commented on src/preprocessing/passes/non_clausal_simp.cpp
>    SubstitutionMap::iterator pos;
This is horrible. This is one iterator used everywhere in this method...

2020-11-12 10:14 UTC, nafur commented on src/preprocessing/passes/non_clausal_simp.cpp
> +  for (pos = nss.begin(); pos != nss.end(); ++pos)
```suggestion
  for (const auto& pos: nss)
```
And replace `(*pos)` by `pos`.

2020-11-12 10:14 UTC, nafur commented on src/preprocessing/passes/non_clausal_simp.cpp
> +  for (pos = cps.begin(); pos != cps.end(); ++pos)
Ditto.

2020-11-12 10:14 UTC, nafur commented on src/preprocessing/passes/non_clausal_simp.cpp
> +  for (pos = nss.begin(); pos != nss.end(); ++pos)
Ditto.

2020-11-12 10:14 UTC, nafur commented on src/preprocessing/passes/non_clausal_simp.cpp
> +  for (pos = cps.begin(); pos != cps.end(); ++pos)
Ditto.

2020-11-12 23:22 UTC, ajreynol commented
I've updated to use local iterators. In this instance I'd prefer not to use auto since its a non-standard object that is being iterated over and it is clearer to me to have the type.

2020-11-14 13:33 UTC, nafur approved these changes
LGTM now.

2020-11-14 14:17 UTC, merged