Add declare model symbol methods to SymbolManager and Model
CVC4/CVC4 pull request #5480
Opened 2020-11-19 22:38 UTC by ajreynol

This is in preparation for the symbol manager determining which symbols are printed in the model.

2020-11-20 09:21 UTC, nafur requested changes
One request. A general question: why not return sorts and terms separately in the SymbolManager as well, just like in the Model?

2020-11-20 09:21 UTC, nafur commented on src/expr/symbol_manager.cpp
> +  }
```suggestion
  declareSorts.insert(declareSorts.end(), d_declareSorts.begin(), d_declareSorts.end());
  declareTerms.insert(declareTerms.end(), d_declareTerms.begin(), d_declareTerms.end());
```

2020-11-20 13:31 UTC, ajreynol commented
I've split the access functions in symbol manager for sorts and terms.

2020-11-22 10:54 UTC, nafur approved these changes
LGTM.

2020-11-23 12:40 UTC, merged