Add BV solver bitblast.
CVC4/CVC4 pull request #5851
Opened 2021-02-03 01:02 UTC by mpreiner

This PR adds a new bit-blasting BV solver, which can be enabled via `--bv-solver=bitblast`. The new bit-blast solver can be used instead of the lazy BV solver and currently supports CaDiCaL and CryptoMiniSat as SAT back end.

2021-02-03 10:37 UTC, martin-cs commented
👀❤️🎉🎉🎉

2021-02-03 15:16 UTC, ajreynol requested changes

2021-02-03 15:16 UTC, ajreynol commented on src/prop/cadical.h
> +  std::vector<SatLiteral> d_assumptions;
Can you add a one line doc on this?

2021-02-03 15:16 UTC, ajreynol commented on src/prop/sat_solver.h
> +  virtual void getUnsatAssumptions(std::vector<SatLiteral>& unsat_assumptions)
Document: what does this correspond to and when are you allowed to call this.

2021-02-03 15:16 UTC, ajreynol commented on src/theory/bv/bitblast/simple_bitblaster.cpp
> +  if (atom.getKind() == kind::NOT)
Can you rename the argument to this method `lit`?  When I see `atom` as an argument this usually needs non-negated.

2021-02-03 15:16 UTC, ajreynol commented on src/theory/bv/bitblast/simple_bitblaster.h
> +  bool isVariable(TNode node);
Document.

2021-02-03 15:16 UTC, ajreynol commented on src/theory/bv/bv_solver_bitblast.cpp
> +  return false;
Can you state why you return false?  (I believe this enables equality engine reasoning, right?)

2021-02-03 19:14 UTC, ajreynol approved these changes
LGTM

2021-02-03 20:38 UTC, merged

2021-02-05 08:11 UTC, florianschanda commented
This looks exciting :)