Refactoring theory inference process
CVC4/CVC4 pull request #5920
Opened 2021-02-18 04:11 UTC by ajreynol

This PR refactors TheoryInference so that it is not responsible for calling back into InferenceManager, instead it sets data so that InferenceManagerBuffered has enough information to do this itself.

Marking as "draft" since there are issues with conjunctive facts that I'd like to safeguard more first.

2021-02-18 16:07 UTC, nafur requested changes
See comments.

2021-02-18 18:09 UTC, ajreynol commented on src/theory/theory_inference_manager.cpp
> +    p = p & LemmaProperty::CACHE;
Yep, whoops.

2021-02-18 18:09 UTC, ajreynol commented on src/theory/arith/nl/ext/monomial_check.cpp
> +                       InferenceId::ARITH_NL_COMPARISON);
Yes, I also noticed this, I agree.

2021-02-18 18:16 UTC, ajreynol commented on src/theory/bags/inference_manager.h
> +  void processLemma(InferInfo& ii);
I agree it should be renamed, good point.  I think I'm also convinced it should go in a generic class, although for now, I'd suggest adding it into InferenceManagerBuffered.  What do you think?

2021-02-18 18:18 UTC, ajreynol commented on src/theory/theory_inference_manager.h
> +                    LemmaProperty p = LemmaProperty::NONE);
Yes, I actually had a version with `LemmaProperty::NO_CACHE`, which meant that `LemmaProperty::NONE` was the default and cached.  This was also confusing.

To be honest, I'm still considering dropping this distinction altogether and saying this is a per-theory and not per-lemma decision.

2021-02-18 19:00 UTC, ajreynol commented on src/theory/arith/nl/transcendental/transcendental_state.cpp
> +      lem, LemmaProperty::CACHE, nullptr, InferenceId::ARITH_NL_T_SECANT);
This would require some deeper refactoring since it is being returned by the method.

2021-02-19 08:39 UTC, nafur approved these changes
LGTM.

2021-02-19 15:26 UTC, merged