Switch to C++17.
CVC4/CVC4 pull request #5959
Opened 2021-02-22 22:12 UTC by mpreiner

2021-02-22 22:15 UTC, nafur approved these changes
LGTM. Yay! 🎉

2021-02-23 07:43 UTC, nafur requested changes
My feeling is that lambdas are usually superior to std::bind in modern C++.
Not only are they far more readable, they are also usually more efficient: lambdas end up to be regular functions that can be inlined.

2021-02-23 07:43 UTC, nafur commented on src/expr/node.h
> +                *this));
How about this?
```suggestion
  Iterator j = find_if(
      substitutionsBegin,
      substitutionsEnd,
      [this](const auto& subst){ return subst.first == *this; });
```

2021-02-23 08:54 UTC, nafur commented
So the next issue: dynamic exception specification was removed with c++17 (i.e. `void f() throw(...)`). As far as I can tell, we didn't use them anyway, except for a few commented out instances in `delta_rational.h`. With this removal, `std::set_unexpected` et al were removed as well, and we can simply remove them from our codebase. Also, we might want to consider marking functions `noexcept`.

2021-02-23 17:37 UTC, nafur approved these changes
LGTM.

2021-02-23 18:32 UTC, ajreynol commented
We should performance test SMT-LIB quantifiers, where substitute can be a bottleneck

2021-02-23 20:53 UTC, ajreynol commented
Nevermind, the changed variant of substitute is not the commonly used one.

2021-02-23 23:56 UTC, merged