Direct lemmas and inference ids for sygus extension
CVC4/CVC4 pull request #5960
Opened 2021-02-23 00:05 UTC by ajreynol

This adds inference ID for the datatypes sygus solver, and changes its style to send lemmas instead of passing them to the caller.

2021-03-10 10:18 UTC, nafur requested changes
A bunch of style issues, but nothing major.

2021-03-10 21:05 UTC, ajreynol commented on src/theory/datatypes/sygus_extension.cpp
> +bool SygusExtension::checkValue(Node n, Node vn, int ind)
n definitely needs to be Node, I'll change vn to TNode.

2021-03-10 21:06 UTC, ajreynol commented on src/theory/datatypes/sygus_extension.cpp
> +void SygusExtension::preRegisterTerm(TNode n)
It is TNode here.

2021-03-11 08:07 UTC, nafur approved these changes
LGTM.

2021-03-11 08:44 UTC, merged