Add utility classes for new statistics
CVC4/CVC4 pull request #6178
Opened 2021-03-18 22:55 UTC by nafur

This PR introduces two new sets of classes used for the new statistics setup.
The first set are the statistic values that hold the actual data and will live in the new statistics registry itself.
The second set are proxy objects: they only hold a pointer to the value classes and implement all the modifiers.

The code is not used yet, but replace the code in the `stats_*` files in a subsequent PR.

2021-03-18 22:56 UTC, nafur commented
Note that the `statistics_stats.*` are not yet registered in cmake. As the classes have the same name as the old ones, this would result in linker errors...

2021-03-26 16:28 UTC, aniemetz requested changes

2021-03-26 16:28 UTC, aniemetz commented on src/base/configuration.h
> +  static constexpr bool isStatisticsBuild() {
Format

2021-03-26 16:28 UTC, aniemetz commented on src/util/statistics_stats.cpp
> +}
```suggestion
}

```

2021-03-26 16:28 UTC, aniemetz commented on src/util/statistics_stats.cpp
> +}
```suggestion
}

```

2021-03-26 16:28 UTC, aniemetz commented on src/util/statistics_stats.cpp
> +}
```suggestion
}

```

2021-03-26 16:28 UTC, aniemetz commented on src/util/statistics_stats.cpp
> +}
```suggestion
}

```

2021-03-26 16:28 UTC, aniemetz commented on src/util/statistics_stats.cpp
> +}
```suggestion
}

```

2021-03-26 16:28 UTC, aniemetz commented on src/util/statistics_stats.cpp
> +    AlwaysAssert(d_data->d_running) << "timer not running";
This doesn't have to be an `AlwaysAssert`. Rather, it probably shouldn't.

2021-03-26 16:28 UTC, aniemetz commented on src/util/statistics_stats.h
> +  stat_type* d_data;
Document

2021-03-26 16:28 UTC, aniemetz commented on src/util/statistics_stats.h
> +  stat_type* d_data;
Document

2021-03-26 16:28 UTC, aniemetz commented on src/util/statistics_stats.h
> +  stat_type* d_data;
Document

2021-03-26 16:28 UTC, aniemetz commented on src/util/statistics_stats.h
> +  stat_type* d_data;
Document

2021-03-26 16:28 UTC, aniemetz commented on src/util/statistics_stats.h
> +  bool d_reentrant;
Document

2021-03-26 16:28 UTC, aniemetz commented on src/util/statistics_stats.h
> +  /** Start the timer */
Document `allow_reentrant`.

2021-03-26 16:28 UTC, aniemetz commented on src/util/statistics_stats.h
> +    }
```suggestion
    return T();
```

2021-03-26 16:28 UTC, aniemetz commented on src/util/statistics_value.cpp
> +void StatisticAverageValue::printSafe(int fd) const
Add lines between functions (below, too).

2021-03-26 16:28 UTC, aniemetz commented on src/util/statistics_value.h
> +  bool d_expert = true;
Move documentation from above to down here and document each.

2021-03-26 16:28 UTC, aniemetz commented on src/util/statistics_value.h
> +      }
```suggestion
      return *d_committed;
```

2021-03-26 16:28 UTC, aniemetz commented on src/util/statistics_value.h
> +      }
```suggestion
      return *d_value;
```

2021-03-26 16:28 UTC, aniemetz commented on src/util/statistics_value.h
> +  bool d_running;
Document

2021-04-01 18:39 UTC, aniemetz approved these changes

2021-04-01 22:40 UTC, merged